language: rust

sudo: false

notifications:
    email:
        on_success: never
        on_failure: change

branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Build pull requests.
    - master

rust:
    - nightly

os:
  - linux
  - osx
  - windows

cache:
  branch: bash
  cargo: true
  directories:
    - ${TRAVIS_HOME}/Library/Caches/Homebrew

addons:
  apt:
    packages:
      - qemu-system-x86
  homebrew:
    packages:
      - qemu

install:
  - ls ${TRAVIS_HOME}/.cargo/bin
  - cargo install --list
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install qemu; export PATH="/c/Program Files/qemu:$PATH"; fi

before_script:
  - rustup component add rust-src
  - (test -x ${TRAVIS_HOME}/.cargo/bin/cargo-install-latest || test -x ${TRAVIS_HOME}/.cargo/bin/cargo-install-latest.exe || cargo install cargo-install-latest)
  - cargo install-latest cargo-xbuild bootimage
  - ls ${TRAVIS_HOME}/.cargo/bin
  - cargo install --list

script:
  - bootimage build
  - cargo test
  - bootimage test
